spring:
  application:
    name: forum
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3336/forum
    username: root
    password: 123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
#    database-platform: org.hibernate.dialect.H2Dialect
jwt:
  secret: uEAhVLWKWpXCd/8S7VcsHfyYpZmoaLFcrvTzzBSB555GMSyJuMS5h5dWu4y/CtYxjhGll5czQfNy1Gp1g23VQA==
